name: Build and Auto-Merge

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.21.0"

      - name: Build
        run: go build -v ./

      - name: Test
        run: go test ./cmd -v -json > TestResults-1.21.0.json

      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-1.21.0
          path: TestResults-1.21.0.json
          
      # Only run auto-merge steps for dependabot PRs
      - name: Check if Dependabot PR
        id: dependabot-check
        if: ${{ github.event_name == 'pull_request' && github.actor == 'dependabot[bot]' }}
        run: echo "is_dependabot=true" >> $GITHUB_OUTPUT

      - name: Dependabot metadata
        id: metadata
        if: ${{ steps.dependabot-check.outputs.is_dependabot == 'true' }}
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      
      - name: Auto-merge Dependabot PRs
        # Only merge if tests passed and it's not a major version update
        if: ${{ steps.dependabot-check.outputs.is_dependabot == 'true' && steps.metadata.outputs.update-type != 'version-update:semver-major' }}
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}