name: Dependabot Auto-Merge

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.0"

      - name: Build
        run: go build -v ./

      - name: Test
        run: go test ./cmd -v

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      
      - name: Auto-merge Dependabot PRs
        # Only merge if tests passed and it's not a major version update
        if: ${{ success() && steps.metadata.outputs.update-type != 'version-update:semver-major' }}
        run: gh pr merge --auto "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
